#
# Ci-dessous la config qui permet de lancer ia rameau (4 conteneurs)
#
# Remarque: avant de lancer docker-compose up, il faut régler le fichier .env
# en partant du fichier .env-dist qui donne les variables d'environnements
# à personnaliser et des exemples de valeurs.
#


services:


  iar-batch-dump:
    image: abesesr/iar:${IAR_BATCH_DUMP_VERSION}
    container_name: iar-batch-dump
    restart: unless-stopped
    mem_limit: ${MEM_LIMIT}
    memswap_limit: ${MEM_LIMIT}
    cpus: ${CPU_LIMIT}
    environment:   
      IAR_BATCH_SPRING_PROFILES_ACTIVE: ${IAR_BATCH_SPRING_PROFILES_ACTIVE}
      IAR_BATCH_JAVA_TOOL_OPTIONS: ${IAR_BATCH_JAVA_TOOL_OPTIONS}
      IAR_BATCH_OUTPUT_DIR: ${IAR_BATCH_OUTPUT_DIR}
      IAR_BATCH_UPLOAD_URL: ${IAR_BATCH_UPLOAD_URL}
      IAR_BATCH_VECTORIZATION_URL: ${IAR_BATCH_VECTORIZATION_URL}
      IAR_BATCH_CHUNK_SIZE: ${IAR_BATCH_CHUNK_SIZE}
      IAR_BATCH_SOURCE_TABLE: ${IAR_BATCH_SOURCE_TABLE}
      IAR_BATCH_TEST_OUTPUT_DIR: ${IAR_BATCH_TEST_OUTPUT_DIR}
      ORACLE_HOST: ${ORACLE_HOST}
      ORACLE_PORT: ${ORACLE_PORT}
      ORACLE_SERVICE: ${ORACLE_SERVICE}
      ORACLE_USER: ${ORACLE_USER}
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
    volumes: 
      - ./volumes:/app/data
    networks :
      -  ${IAR_DOCKER_NETWORK}     
    labels:
      # pour envoyer les logs dans le puits de log de l'abes
      - "co.elastic.logs/enabled=true"
      - "co.elastic.logs/processors.add_fields.target="
      - "co.elastic.logs/processors.add_fields.fields.abes_appli=iar"
      - "co.elastic.logs/processors.add_fields.fields.abes_middleware=java-spring"
      # pour que les mises à jour de cette image soient auto-déployées par wud
      - "wud.watch=true"
      - "wud.watch.digest=true"


  iar-vectorisation:
    image: abesesr/iar:${IAR_VECTORISATION_VERSION}
    container_name: iar-vectorisation
    restart: unless-stopped
    mem_limit: ${MEM_LIMIT}
    memswap_limit: ${MEM_LIMIT}
    cpus: ${CPU_LIMIT}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
     # TODO verif llm necessaire ou non pour  la vectorisation 
      IAR_QDRANT_HOST: ${IAR_QDRANT_HOST}
      IAR_QDRANT_PORT: ${IAR_QDRANT_PORT}
      IAR_QDRANT_MIN_VECTORS: ${IAR_QDRANT_MIN_VECTORS}
      IAR_QDRANT_TEST_LIMIT: ${IAR_QDRANT_TEST_LIMIT}

      IAR_DOCKER_VOLUME_BIND: ${IAR_DOCKER_VOLUME_BIND} 

      IAR_VECTORIZE_CONCEPTS_OR_CHAINS: ${IAR_VECTORIZE_CONCEPTS_OR_CHAINS}      
      IAR_VECTORIZE_AVEC_THESE: ${IAR_VECTORIZE_AVEC_THESE} 

      IAR_VECTORISATION_HOST: ${IAR_VECTORISATION_HOST}
      IAR_VECTORISATION_PORT: ${IAR_VECTORISATION_PORT}
      IAR_DOCKER_NETWORK: ${IAR_DOCKER_NETWORK}
      IAR_DOCKER_IMAGE_BATCH: ${IAR_DOCKER_IMAGE_BATCH}
      IAR_DOCKER_SOCK: ${IAR_DOCKER_SOCK}
      IAR_DOCKER_BATCH_USER : ${IAR_DOCKER_BATCH_USER}
      
      ENABLE_GPU: ${ENABLE_GPU}
    depends_on:
      - iar-qdrant
    user: root
    ports:
      - ${IAR_VECTORISATION_PORT}:${IAR_VECTORISATION_PORT}
    volumes: 
      - ./volumes:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks :
      -  ${IAR_DOCKER_NETWORK}
    labels:
      # pour envoyer les logs dans le puits de log de l'abes
      - "co.elastic.logs/enabled=true"
      - "co.elastic.logs/processors.add_fields.target="
      - "co.elastic.logs/processors.add_fields.fields.abes_appli=iar"
      - "co.elastic.logs/processors.add_fields.fields.abes_middleware=fastapi"
      # pour que les mises à jour de cette image soient auto-déployées par wud
      - "wud.watch=true"
      - "wud.watch.digest=true"

  iar-qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    container_name: iar-qdrant
    ports:
      - ${IAR_QDRANT_PORT}:6333  
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./volumes/qdrant/storage:/qdrant/storage
    networks :
      -  ${IAR_DOCKER_NETWORK}
  iar-llm:
    image: ollama/ollama:latest
    container_name: iar-llm
    restart: unless-stopped
    mem_limit: ${MEM_LIMIT}
    memswap_limit: ${MEM_LIMIT}
    cpus: ${CPU_LIMIT}
    ports:
      - ${IAR_LLM_PORT}:11434
    volumes:
      - ./volumes/ollama:/root/.ollama
    networks:
      -  ${IAR_DOCKER_NETWORK}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  iar-api:
    image: abesesr/iar:${IAR_API_VERSION}
    container_name: iar-api
    restart: unless-stopped
    mem_limit: ${MEM_LIMIT}
    memswap_limit: ${MEM_LIMIT}
    cpus: ${CPU_LIMIT}
    environment:
      IAR_API_LLM_URL : ${IAR_LLM_URL}
      IAR_API_LLM_KEY: ${IAR_LLM_KEY}
      IAR_API_LLM_MODEL: ${IAR_LLM_MODEL}
      IAR_QDRANT_HOST: ${IAR_QDRANT_HOST}
      IAR_QDRANT_PORT: ${IAR_QDRANT_PORT}
      IAR_API_HTTP_HOST: ${IAR_API_HTTP_HOST}
      IAR_API_HTTP_PORT: ${IAR_API_HTTP_PORT}
      IAR_CORS_ORIGINS: ${IAR_CORS_ORIGINS}
    ports:
      - ${IAR_API_HTTP_PORT}:${IAR_API_HTTP_PORT}
    volumes:
      - ./volumes:/app/data:z
    depends_on:
      - iar-llm
      - iar-qdrant
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks :
      -  ${IAR_DOCKER_NETWORK}
    labels:
      # pour envoyer les logs dans le puits de log de l'abes
      - "co.elastic.logs/enabled=true"
      - "co.elastic.logs/processors.add_fields.target="
      - "co.elastic.logs/processors.add_fields.fields.abes_appli=iar"
      - "co.elastic.logs/processors.add_fields.fields.abes_middleware=fastapi"
      # pour que les mises à jour de cette image soient auto-déployées par wud
      - "wud.watch=true"
      - "wud.watch.digest=true"

configs:
  qdrant_config:
    content: |
      log_level: INFO

networks : 
  iar-network :
    name : ${IAR_DOCKER_NETWORK}
    external : true


      