#
# Ci-dessous la config qui permet de lancer ia rameau (4 conteneurs)
#
# Remarque: avant de lancer docker-compose up, il faut régler le fichier .env
# en partant du fichier .env-dist qui donne les variables d'environnements
# à personnaliser et des exemples de valeurs.
#


services:


  iar-batch-dump:
    image: abesesr/iar:${IAR_BATCH_DUMP_VERSION}
    container_name: iar-batch-dump
    restart: unless-stopped
    mem_limit: ${MEM_LIMIT}
    memswap_limit: ${MEM_LIMIT}
    cpus: ${CPU_LIMIT}
    environment:   
      SPRING_PROFILES_ACTIVE: ${IAR_SPRING_PROFILES_ACTIVE}
    volumes: 
     - ${IAR_DATA_DIR}:./volumes 
    networks :
      -  ${IAR_DOCKER_NETWORK}     
    labels:
      # pour envoyer les logs dans le puits de log de l'abes
      - "co.elastic.logs/enabled=true"
      - "co.elastic.logs/processors.add_fields.target="
      - "co.elastic.logs/processors.add_fields.fields.abes_appli=iar"
      - "co.elastic.logs/processors.add_fields.fields.abes_middleware=java-spring"
      # pour que les mises à jour de cette image soient auto-déployées par wud
      - "wud.watch=true"
      - "wud.watch.digest=true"


  iar-vectorisation:
    image: abesesr/iar:${IAR_VECTORISATION_VERSION}
    container_name: iar-vectorisation
    restart: unless-stopped
    mem_limit: ${MEM_LIMIT}
    memswap_limit: ${MEM_LIMIT}
    cpus: ${CPU_LIMIT}
    environment:
     # TODO verif llm necessaire ou non pour  la vectorisation 
      IAR_QDRANT_HOST: ${IAR_QDRANT_HOST}
      IAR_QDRANT_PORT: ${IAR_QDRANT_PORT}
      IAR_QDRANT_MIN_VECTORS: ${IAR_QDRANT_MIN_VECTORS}
      IAR_QDRANT_TEST_LIMIT: ${IAR_QDRANT_TEST_LIMIT}

      IAR_DATA_DIR: ${IAR_DATA_DIR}    
      IAR_DOCKER_VOLUME_BIND: ${IAR_DOCKER_VOLUME_BIND} 

      IAR_VECTORIZE_CONCEPTS_OR_CHAINS: ${IAR_VECTORIZE_CONCEPTS_OR_CHAINS}      
      IAR_VECTORIZE_AVEC_THESE: ${IAR_VECTORIZE_AVEC_THESE} 

      IAR_VECTORISATION_HOST: ${IAR_VECTORISATION_HOST}
      IAR_VECTORISATION_PORT: ${IAR_VECTORISATION_PORT}

      IAR_CSV_DIR: ${IAR_CSV_DIR}
      IAR_PKL_DIR: ${IAR_PKL_DIR}

      IAR_DOCKER_NETWORK: ${IAR_DOCKER_NETWORK}
      IAR_DOCKER_IMAGE_BATCH: ${IAR_DOCKER_IMAGE_BATCH}
      IAR_DOCKER_SOCK=: ${IAR_DOCKER_SOCK}

      ENABLE_GPU: ${ENABLE_GPU}

    user: root
    ports:
      - ${IAR_VECTORISATION_PORT}:80
    volumes: 
      - ${IAR_DATA_DIR}:./volumes
      - /var/run/docker.sock:/var/run/docker.sock
    networks :
      -  ${IAR_DOCKER_NETWORK}
    labels:
      # pour envoyer les logs dans le puits de log de l'abes
      - "co.elastic.logs/enabled=true"
      - "co.elastic.logs/processors.add_fields.target="
      - "co.elastic.logs/processors.add_fields.fields.abes_appli=iar"
      - "co.elastic.logs/processors.add_fields.fields.abes_middleware=fastapi"
      # pour que les mises à jour de cette image soient auto-déployées par wud
      - "wud.watch=true"
      - "wud.watch.digest=true"

  iar-qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    container_name: iar-qdrant
    ports:
      - ${IAR_QDRANT_PORT}:6333  
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:./volumes/qdrant/storage
    networks :
      -  ${IAR_DOCKER_NETWORK}

  iar-api:
    image: abesesr/iar:${IAR_API_VERSION}
    container_name: iar-api
    restart: unless-stopped
    mem_limit: ${MEM_LIMIT}
    memswap_limit: ${MEM_LIMIT}
    cpus: ${CPU_LIMIT}
    environment:
      IAR_API_LLM_URL : ${IAR_LLM_URL}
      IAR_API_LLM_KEY: ${IAR_LLM_KEY}
      IAR_API_LLM_MODEL: ${IAR_LLM_MODEL}
      IAR_QDRANT_HOST: ${IAR_QDRANT_HOST}
      IAR_QDRANT_PORT: ${IAR_QDRANT_PORT}
    ports:
      - ${IAR_API_HTTP_PORT}:80
    #depends_on:
      #- licencesnationales-web
    networks :
      -  ${IAR_DOCKER_NETWORK}
    labels:
      # pour envoyer les logs dans le puits de log de l'abes
      - "co.elastic.logs/enabled=true"
      - "co.elastic.logs/processors.add_fields.target="
      - "co.elastic.logs/processors.add_fields.fields.abes_appli=iar"
      - "co.elastic.logs/processors.add_fields.fields.abes_middleware=fastapi"
      # pour que les mises à jour de cette image soient auto-déployées par wud
      - "wud.watch=true"
      - "wud.watch.digest=true"

configs:
  qdrant_config:
    content: |
      log_level: INFO

networks : 
  iar-network :
    name : ${IAR_DOCKER_NETWORK}
    external : true


      